### ISSUE TITLE
DELETE method

### ISSUE THREAD

**Issue by wesleymilan** [strongloop/loopback-example-database#20]
When using API Explorer everything works fine, but when using Angular SDK none module allow delete method with destroyById() function

loopback:connector:mysql Data:  +2ms [ { id: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ttl: 999999999,
    created: Fri Aug 14 2015 02:48:12 GMT+0000 (UTC),
    userId: 'XXXXXXXXXXXXXXXXXXXXXXXXXX' } ]
  express:router dispatching DELETE /ModelLanguages +0ms
  express:router <anonymous>  : /spa/ModelLanguages +0ms
  express:router <anonymous>  : /spa/ModelLanguages +0ms
  express:router urlencodedParser  : /spa/ModelLanguages +1ms
  body-parser:urlencoded skip empty body +0ms
  express:router jsonParser  : /spa/ModelLanguages +0ms
  body-parser:json skip empty body +0ms
  express:router trim prefix (/ModelLanguages) from url /ModelLanguages +0ms
  express:router router /ModelLanguages : /spa/ModelLanguages +0ms
  express:router dispatching DELETE / +0ms
  express:router restRemoteMethodNotFound  : /spa/ModelLanguages +0ms
  express:router restUrlNotFound  : /spa/ModelLanguages +1ms
  express:router restErrorHandler  : /spa/ModelLanguages +0ms
  strong-remoting:rest-adapter Error in DELETE /ModelLanguages: Error: Shared class "ModelLanguage" has no method handling DELETE /
    at restRemoteMethodNotFound (/var/www/api.io/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:322:17)
    at Layer.handle [as handle_request] (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)
    at /var/www/api.apiot.io/node_modules/loopback/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)
    at router (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/api.io/node_modules/loopback/node_modules/express/lib/router/index.js:312:13) +0ms
  compression gzip compression +2ms

**Comment by mariohmol** [comment]
how did u fixed?

**Comment by mbenedettini** [comment]
For anybody running into the same issue: this happens when you issue `Model.destroyById(1234)`, instead pass the id as an object: `Model.destroyById({id: 1234})`

**Comment by cemturk** [comment]
Thx for the solution @mbenedettini I had the same issue, sadly there is no mention of this behaviour anywhere

**Comment by superkhau** [comment]
Would someone like to submti a PR to fix this? @crandmck Can we document this for now so there are no suprises.

**Comment by crandmck** [comment]
Actually, this signature appears to be documented in https://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Delete.

This would be easier to document if we could still provide the Angular client SDK API docs.  Unfortunately, that and the `lb-ng-doc` tool were both casualties of copyright issues.
