### ISSUE TITLE
Connection fails: Error: Handshake inactivity timeout in loopback

### ISSUE THREAD

**Issue by arvindkrbhatt** [strongloop/loopback-example-database#58]
Hi,
 I have installed Node.js version 6.9.0 on my machine. I am trying to run sample for SQL database connectivity from examples. I am getting "Connection fails: Error: Handshake inactivity timeout" when i launch application. Unfortunately increasing connectionTimeOut, I am getting same error. my colleagues also facing the same problem with sample https://github.com/strongloop/loopback-example-database/tree/MySQL.  please help

regards
 arvind

**Comment by lavish-agrawal** [comment]
When I try to run 'node .' after setting up the data source, I get the following log in the terminal:


Browse your REST API at http://localhost:3000/explorer
Connection fails: Error: Handshake inactivity timeout
It will be retried for the next request.
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/home/ubuntu/loopback-getting-started/node_modules/mysql/lib/protocol/Protocol.js:164:17)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:188:7)
    at Handshake._onTimeout (/home/ubuntu/loopback-getting-started/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
    --------------------
    at Protocol._enqueue (/home/ubuntu/loopback-getting-started/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/ubuntu/loopback-getting-started/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/ubuntu/loopback-getting-started/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/ubuntu/loopback-getting-started/node_modules/mysql/lib/Pool.js:48:16)
    at MySQL.connect (/home/ubuntu/loopback-getting-started/node_modules/loopback-connector-mysql/lib/mysql.js:89:17)
at Object.initializeDataSource [as initialize] (/home/ubuntu/loopback-getting-started/node_modules/loopback-connector-mysql/lib/mysql.js:43:28)
    at DataSource.setup (/home/ubuntu/loopback-getting-started/node_modules/loopback-datasource-juggler/lib/datasource.js:417:19)
    at new DataSource (/home/ubuntu/loopback-getting-started/node_modules/loopback-datasource-juggler/lib/datasource.js:123:8)
    at Registry.createDataSource (/home/ubuntu/loopback-getting-started/node_modules/loopback/lib/registry.js:360:12)
    at dataSourcesFromConfig (/home/ubuntu/loopback-getting-started/node_modules/loopback/lib/application.js:512:19)
    at Function.app.dataSource (/home/ubuntu/loopback-getting-started/node_modules/loopback/lib/application.js:229:14)
    at /home/ubuntu/loopback-getting-started/node_modules/loopback-boot/lib/executor.js:191:9
    at /home/ubuntu/loopback-getting-started/node_modules/loopback-boot/lib/executor.js:282:5
    at Array.forEach (native)
    at forEachKeyedObject (/home/ubuntu/loopback-getting-started/node_modules/loopback-boot/lib/executor.js:281:20)
    at setupDataSources (/home/ubuntu/loopback-getting-started/node_modules/loopback-boot/lib/executor.js:181:3)
